name:                dick
version:             0.1.0.0
github:              "lambdalainen/dick"
license:             BSD3
author:              "Yifan Yu"
maintainer:          "yvifan@gmail.com"
copyright:           "Copyright @ 2019 Yifan Yu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lambdalainen/dick#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- filepath
- http-client
- http-client-tls
- http-types
- pretty
- uri-encode

library:
  source-dirs: src

executables:
  dick:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dick

tests:
  dick-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dick
